config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#root"
  resources :contact_forms, only: :create
end

app/models/contact_form.rb
class ContactForm < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i

  attribute :subject
  attribute :message

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "#{subject}",
      :to => "bhavikpatel576@gmail.com",
      :from => %("#{name}" <#{email}>),
      :message => "#{message}"
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_forms_controller.rb
class ContactFormsController < ApplicationController
  def create
    @contact_form = ContactForm.new(params[:contact_form])
    @contact_form.request = request
    if @contact_form.deliver
      flash[:notice] = "Thank you for your message - I'll be in touch soon!"
      redirect_to root_url
    else
      flash[:notice] = 'Oh no - something went wrong! Try again!'
      redirect_to '/#contact'
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def root; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_forms_helper.rb
module ContactFormsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_flash_messages.html.erb
<% unless flash[:notice].nil? %>
  <div
    class="alert alert-dismissible"
    id="error"
    role="alert">
     <button
       type="button"
       class="close"
       data-dismiss="alert">
       <span aria-hidden="true" id="close">&times;</span>
     </button>
   <span id="alert-text"><%= flash[:notice]%></span>
 </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>B Patel | A Portfolio</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <title>B Patel | A Portfolio</title>
  <meta name="description" content="" />
  <meta name="keywords" content="" />
  <link
    rel="shortcut icon"
    type="image/ico"
    href="../assets/favicon.png" />
      <!--[if lte IE 8]><link rel="stylesheet" href="css/ie/v8.css" /><![endif]-->
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','__gaTracker');

      __gaTracker('create', 'UA-49503804-2', 'auto');
      __gaTracker('send', 'pageview');

    </script>
</head>
<body>

<%= render 'layouts/flash_messages' %>

<%= yield %>

</body>
</html>

app/views/static_pages/_about.html.erb
<section>
  <div class="row">
    <div class="4u image">
      <img src="../assets/bhavik_coding.jpg" alt="">
    </div>
    <h2 id="about">About Bhavik</h2>
    <p id="resume">
      <%=
        link_to 'Resume',
        asset_path("Bpatel-Resume.pdf"),
        :target => "_blank"
      %>
    </p>
    <div class="description-div">
      <p class="description about">
        I love to run, hike, and just generally be outdoors. I think my greatest strength is consistantly putting myself in uncomfortable situations when things get comfortable. In my previous life I worked as an analyst in various financial roles, but now i’m an aspiring Software Developer in training to build web products to make peoples' life easier. 
      </p>
      <p class="description about">
Currently living in <span>San Francisco</span>,
      </p>
      <p id="email">
        bhavikpatel576@gmail.com
      </p>
    </div>
  </div>
</section>

app/views/static_pages/_artifacts.html.erb
<header>
  <h2>Blog</h2>
</header>
<p>
Links to some random blog entries that i've written.
<li>
    <a href ="https://medium.com/@bhavikpatel576/single-inheritance-1d3c8960beb5"> Single Inheritance Model in Ruby </a>
</li>
</p>
<section>
  <div class="row">
    <div class="4u">
      <div class="image fit no-shadow">
      </div>
    </div>
    <div class="4u">
      <div class="image fit no-shadow">
      </div>
    </div>
    <div class="4u">
      <div class="image fit no-shadow">
      </div>
    </div>
  </div>
  <div class="row">
    <div class="4u">
      <div class="image fit no-shadow">
      </div>
    </div>
    <div class="4u">
      <div class="image fit no-shadow">
      </div>
    </div>
    <div class="4u">
      <div class="image fit no-shadow">
      </div>
    </div>
  </div>
  <div class="row">
    <div class="4u">
      <div class="image fit no-shadow">
      </div>
    </div>
    <div class="4u">
      <div class="image fit no-shadow">
      </div>
    </div>
    <div class="4u">
      <div class="image fit no-shadow">
      </div>
    </div>
  </div>
</section>

app/views/static_pages/_contact.html.erb
<header>
  <h2>Contact Me</h2>
</header>
<form action="<%= contact_forms_url %>" method="post">
  <input
    type='hidden'
    name='authenticity_token'
    value='form_authenticity_token'>
  <div>
    <div class="row">
      <div class="6u">
        <input
          type="text"
          name="contact_form[name]"
          placeholder="Name" />
      </div>
      <div class="6u">
        <input
        type="text"
        name="contact_form[email]"
        placeholder="Email" />
      </div>
    </div>
    <div class="row">
      <div class="12u">
        <input
          type="text"
          name="contact_form[subject]"
          placeholder="Subject" />
      </div>
    </div>
    <div class="row">
      <div class="12u">
        <textarea
          name="contact_form[message]"
          placeholder="Message" rows="8"></textarea>
      </div>
    </div>
    <div class="row">
      <div class="12u">
        <input type="submit" value="Send Message" />
      </div>
    </div>
  </div>
</form>

app/views/static_pages/_footer.html.erb
<div id="footer">
  <ul class="copyright">
    <li class="footer-icons">
      <a
        href="https://www.linkedin.com/in/bhavikpatel576"
        target="_blank">
        <i class="fa fa-linkedin-square"></i>
      </a>
    </li>
    <li>&copy; Bhavik Patel.</li>
    <li>Design:
      <a
        href="http://html5up.net"
        target="_blank">
        HTML5 UP
      </a>
    </li>
    <li class="footer-icons">
      <a
        href="http://github.com/bhavikpatel576"
        target="_blank"
        >
        <i class="fa fa-github-square"></i>
      </a>
    </li>
  </ul>
</div>

app/views/static_pages/_me.html.erb
<header>
  <h1>Bhavik Patel</h1>
  <p>Full Stack Developer</p>
</header>
<a href="#work" class="jumplink pic">
  <img src="../assets/bhavik_coding.jpg" alt="" />
</a>

app/views/static_pages/_nav.html.erb
<nav id="nav">
  <a href="#me" class="active">
    <i class="fa fa-home"></i>
    <span>Home</span>
  </a>
  <a href="#work">
    <i class="fa fa-code"></i>
    <span>Projects</span>
  </a>
  <a href="#artifacts" class="icon fa-cube">
    <i class="fa fa-cube"></i>
    <span>Blog</span>
  </a>
  <a href="#about" class="icon fa-heart-o">
    <i class="fa fa-heart-o"></i>
    <span>About</span>
  </a>
  <!-- <a href="#contact" class="icon fa-envelope">
    <i class="fa fa-envelope"></i>
    <span>Contact</span>
  </a> -->
</nav>

app/views/static_pages/_work.html.erb
<header>
  <h2>Projects</h2>
</header>
<p>
  A selection of fun apps I've made. Ask me about what I'm working on now!
</p>
<section>

  <div class="row">
    <div class="4u alt">
      <a
        class="image fit"
        target="_blank">
        <img src="https://thumbs.gfycat.com/ThriftyQuaintGalah-size_restricted.gif" alt="">
      </a>
    </div>
    <div class="description-div">
      <h3>3D-Wireframe</h3>
      <a
        href="https://github.com/Bhavikpatel576/42/tree/master/FdF"
        target="_blank">
        Github
      </a>
      <p class="description">
        Built a 3d wireframe work with C and the mlx library for the graphics engine.
      </p>
      <ul>
        <li>
          ▹ Implemented Bresenham's line algorithm
        </li>
        <li>
          ▹ Project demonstrates one's ability to understand and create space perspective within a 2D plane 
        </li>
        <li>
          ▹ Graphics engine is leveraged off the minilibx library that is a simple x-window programming API in C.
        </li>
      </ul>
    </div>
  </div> <!-- Closed tags for 3D wireframework -->

<div class="row">
    <div class="4u">
      <a
        class="image fit"
        target="_blank">
        <img src="../assets/Fractal2.gif" alt="">
      </a>
    </div>
    <div class="description-div">
      <h3>Julia Set</h3>
      <a
        href="https://github.com/Bhavikpatel576/mandelbrot"
        target="_blank">
        Github
      </a>
      <p class="description">
        Program to visulize the Julia Set
      </p>
      <ul>
        <li>
          ▹ Implemented Mandelbrot's escape time algorithm in order to create a visual fractal
        </li>
        <li>
          ▹ Graphics engine is leveraged off the minilibx library that is a simple x-window programming API in C.
        </li>
      </ul>
    </div>
  </div> <!-- Closed tags for Fractal -->

  <div class="row">
    <div class="4u alt">
      <a
        href="https://github.com/Bhavikpatel576/wolfenstein"
        class="image fit" id="chApp"
        target="_blank">
        <img src="../assets/wolf3d.png" alt="">
      </a>
    </div>
    <div class="description-div alt-description">
      <h3>Wolf-3D</h3>
      <a
        href="https://github.com/Bhavikpatel576/wolfenstein"
        target="_blank">
        Github
      </a>
      <p class="description">
        Recreated a portion of the famed 1992 Wolfenstein 3D first person shooter game.
      </p>
      <ul>
        <li>
          ▹ Uses the ray casting technique to represent space and movement
        </li>
        <li>
          ▹ Multithreaded image for optimization amoung 16 cores
        </li>
      </ul>
    </div>
  </div> <!-- Close of Wolf3d -->

  <div class="row">
    <div class="4u">
      <a
        href="https://hangman576.herokuapp.com/"
        class="image fit"
        target="_blank">
        <img src="../assets/hangman.png" alt="">
      </a>
    </div>
    <div class="description-div">
      <h3>Learn To Build a Hangman App!</h3>
      <a
        href="https://hangman576.herokuapp.com/"
        target="_blank">
        Live
      </a>
       ・
      <a
        href="https://github.com/Bhavikpatel576/Hangman"
        target="_blank">
        Github
      </a>
      <p class="description">
        A simple Hangman Application to show students at 42's summer bootcamp how to build an application with Sinatra
      </p>
      <ul>
        <li>
          ▹ Tutorial covers understanding HTTP routes and requests
        </li>
        <li>
          ▹ What templating langauges do. We use erb for this project.
        </li>
        <li>
          ▹ How to use MiniTest for application testing.
        </li>
      </ul>
    </div>
  </div> <!-- Close of Hangman -->
  <!-- Sinatra To-do -->
  <div class="row">
    <div class="4u alt">
      <a
        href="https://bhavik-productivity-app.herokuapp.com/"
        class="image fit"
        target="_blank">
        <img src="../assets/todo_sinatra.png" alt="">
      </a>
    </div>
    <div class="description-div">
      <h3>Todo Application</h3>
      <a
        href="https://bhavik-productivity-app.herokuapp.com/"
        target="_blank">
        Live
      </a>
       ・
      <a
        href="https://github.com/Bhavikpatel576/productivity_app"
        target="_blank">
        Github
      </a>
      <p class="description">
        A Todo App built with Sinatra Microframework, AJAX in order to delete list items, and PostgreSQL
        to store data.
      </p>
      <ul>
        <li>
          ▹ Safely handle inserting parameters into SQL statements with PG::Connection#exec_params.
        </li>
      </ul>
    </div>
  </div> <!-- Close of Sinatra Todo List -->
  <!-- Highcharts graph -->
<div class="row">
    <div class="4u">
      <a
        href="https://fathomless-reef-55968.herokuapp.com/"
        class="image fit"
        target="_blank">
        <img src="../assets/highcharts.png" alt="">
      </a>
    </div>
    <div class="description-div">
      <h3>Highcharts Application</h3>
      <a
        href="https://fathomless-reef-55968.herokuapp.com/"
        target="_blank">
        Live
      </a>
       ・
      <a
        href="https://github.com/Bhavikpatel576/bouquet"
        target="_blank">
        Github
      </a>
      <p class="description">
        A demonstration of using Highcharts to dynamically display JSON data.
      </p>
      <ul>
        <li>
          ▹ Backend uses Node.js to make the API call to requested JSON data and renders with a single route
        </li>
        <li>
          ▹ Highcharts is used to display the data in a dynamic bar chart
        </li>
        <li>
          ▹ Using jQuery's Datepicker widget to select specific dates based off JSON data.
        </li>
      </ul>
    </div>
  </div> <!-- Close of Sinatra Todo List -->

</section>

app/views/static_pages/root.html.erb
<!-- Wrapper-->
<div id="wrapper" style="padding-top: 0;">

  <!-- Nav -->
    <%= render partial: "nav" %>

  <!-- Main -->
    <div id="main">

      <!-- Me -->
        <article id="me" class="panel">
          <%= render partial: "me" %>
        </article>

      <!-- Work -->
        <article id="work" class="panel">
          <%= render partial: "work" %>
        </article>

      <!-- Artifacts -->
        <article id="artifacts" class="panel">
          <%= render partial: "artifacts" %>
        </article>

      <!-- About -->
        <article id="about" class="panel">
           <%= render partial: "about" %>
        </article>

      <!-- Contact -->
        <!-- <article id="contact" class="panel">
           <%= render partial: "contact" %>
        </article> -->

    </div>

  <!-- Footer -->
    <%= render partial: "footer" %>
</div>